# frozen_string_literal: true

source 'https://rubygems.org'

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

group :development do
  gem 'irb', require: false
end

group :development, :test do
  gem 'rubocop'
end
